
name: Cppcheck - StaticCode analysis
 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

jobs:
  cppcheck:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install cppcheck
      run: sudo apt-get install cppcheck
    - name: Run cppcheck
      run: cppcheck 3_Implementation
 
